#!/bin/bash
# Generate vendor blobs makefiles for Lenovo TB335FC (sycamore)
# Run this after extract-files.sh
# Usage: ./setup-makefiles.sh

set -e
VENDOR_DIR="$(dirname "$0")/../../../vendor/lenovo/sycamore"
PROPRIETARY_FILES="$(dirname "$0")/proprietary-files.txt"

mkdir -p "$VENDOR_DIR"

echo "Generating $VENDOR_DIR/Android.mk"
cat > "$VENDOR_DIR/Android.mk" <<'MAKEFILE'
# Auto-generated by setup-makefiles.sh - do not edit
LOCAL_PATH := $(call my-dir)
MAKEFILE
echo "Done"
