DEVICE_PATH := device/lenovo/sycamore
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)
$(call inherit-product, vendor/twrp/config/common.mk)
$(call inherit-product, $(DEVICE_PATH)/device.mk)
PRODUCT_DEVICE := sycamore
PRODUCT_NAME := twrp_sycamore
PRODUCT_BRAND := Lenovo
PRODUCT_MODEL := TB335FC
PRODUCT_MANUFACTURER := LENOVO
PRODUCT_RELEASE_NAME := TB335FC
AB_OTA_UPDATER := true
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := zh_CN
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1024
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TW_NO_USB_STORAGE := false
TW_HAS_UFS := false
TW_NO_SCREEN_BLANK := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_USE_F2FS_DATA := true
TW_HAS_MTP := false
TW_NO_USB_STORAGE := true
TARGET_RECOVERY_DEVICE_MODULES += init.recovery.usb.configfs.rc
TW_EXCLUDE_MTP := true
